spring:
  datasource:
    url: jdbc:h2:file:~/springboot;AUTO_SERVER=TRUE;
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sql:
    init:
      mode: always